sudo: false

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - cmake
            - cmake-data
            
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=debug
  - make
